import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="assets/css/swiper-bundle.min.css" />
        <link rel="stylesheet" href="assets/css/style.css" />
        <link rel="stylesheet" href="dist/output-scss.css" />
        <link rel="stylesheet" href="dist/output-tailwind.css" />
      </head>
      <body className={inter.className}>{children}</body>
      <Script src="assets/js/phosphor-icons.js" />
      <Script src="assets/js/swiper-bundle.min.js" />
      <Script src="assets/js/main.js" />
    </html>
  );
}
